name: CI/CD Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Save image
      run: docker save myapp | gzip > myapp.tar.gz

    - name: Copy to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "myapp.tar.gz"
        target: "~/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load < myapp.tar.gz
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 5000:5000 \
            -e NOME=Production \
            --restart always \
            --name myapp myapp